# Generated by Django 5.0.1 on 2024-01-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('item_code', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('item_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(default='goods', max_length=255)),
                ('url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('alias', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('stock_category', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('uom', models.CharField(blank=True, max_length=20, null=True)),
                ('valuation_method', models.CharField(default='FIFO', max_length=255)),
                ('opening', models.FloatField(blank=True, default=0, null=True)),
                ('available_quantity', models.FloatField(blank=True, default=0, null=True)),
                ('total_quantity', models.FloatField(blank=True, default=0, null=True)),
                ('cost_price', models.FloatField(blank=True, default=0, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('selling_price', models.FloatField(blank=True, default=0, null=True)),
                ('vat', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('is_fixed_asset', models.BooleanField(default=False)),
                ('expire_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('entry_by', models.CharField(blank=True, default='admin', max_length=255, null=True)),
                ('active_status', models.CharField(default='active', max_length=255)),
            ],
        ),
    ]
